global:
  scrape_interval: 15s

scrape_configs:
  
  - job_name: 'node-exporter'
    static_configs:
      - targets:
        # <Node-ip>:9100
        - 192.168.10.120:9100    
        - 192.168.10.121:9100
        - 192.168.10.122:9100
        - 192.168.10.123:9100

  - job_name: 'cadvisor'
    static_configs:
      - targets:
        # <Node-ip>:8080
        - 192.168.10.120:8080
        - 192.168.10.121:8080
        - 192.168.10.122:8080
        - 192.168.10.123:8080
    
  - job_name: 'kube-state-metrics'
    metrics_path: /metrics
    scheme: http
    static_configs:
      # <Node-ip>:<Node-port> kube-state-metrics Service
      - targets: ['192.168.10.120:30808']
