apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
  namespace: monitoring
  labels:
    app: node-exporter
spec:
  selector:
    matchLabels:
      app: node-exporter
  template:
    metadata:
      labels:
        app: node-exporter
    spec:
      hostNetwork: true
      hostPID: true
      tolerations: # Thêm tolerations block
      - key: node-role.kubernetes.io/control-plane 
        operator: Exists
        effect: NoSchedule
      containers:
      - name: node-exporter
        image: quay.io/prometheus/node-exporter:latest
        args:
          - '--path.rootfs=/host'
        volumeMounts:
        - name: rootfs
          mountPath: /host
          readOnly: true
        ports:
        - containerPort: 9100
          hostPort: 9100
      volumes:
      - name: rootfs
        hostPath:
          path: /
          type: Directory
